# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f573366985108bab0d442fc2383e7dd6ebc3400e55e6bce22e426c776e55f108875849f35a597676433218ca4d51c9d7512f01d41245fe4ddb4ee04ae9b7a86

test:
  secret_key_base: 0f1442e616872e69d366f19fa0a3812e1903fd89cd23bba1f0763964f9a1e336c233effc2bf2a199fd1ab024d1807c60a0be34c2fe4475243fc58db733dd137e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
